urls:
  chrome: "https://chrome.google.com/webstore/detail/uoa-mediaplayerplus/oohpedaigajmdamiaboobdjijopldlkd"
  firefox: "https://github.com/acoollevel/uoa-mediaplayer-plus/releases/download/0.3.2/uoa_mediaplayerplus-0.3.2-fx.xpi"
  github: "https://github.com/acoollevel/uoa-mediaplayer-plus"
  discord: "https://discord.gg/sJbs6hu"
  matrix: "https://matrix.to/#/!GVrLieYtoagUolQHhN:matrix.org?via=matrix.org"

collections:
  authors:
    
baseurl: /uoa-mediaplayer-plus